### ISSUE TITLE
New CMOR-build

### ISSUE THREAD

**Issue by wachsylon** [conda-forge/cmor-feedstock#24]
Hi,
as I learned here
#https://github.com/conda-forge/cdo-feedstock/pull/79
I need a new build from CMOR in order to build it successfully with CDO.

When I try to build this feedstock repo locally by
`conda-build .`
, I receive several warnings.
```
WARNING (cmor): dso library package defaults::libgfortran-ng-7.3.0-hdf63c60_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (cmor): dso library package defaults::python-3.6.10-h7579374_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (cmor): dso library package defaults::hdf5-1.10.4-hb1b8bf9_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```
and I fail because the shared netcdf library could not be loaded in the test.
`ImportError: libnetcdf.so.13: cannot open shared object file: No such file or directory`

When I looked at the meta.yaml, I thought that this might be one netCDF too much so I removed netcdf4 and the build worked. It also works when `hdf5` is additionally removed from the `meta.yaml`. However, when I execute a PrePARE test, I ran into a
`UnicodeDecodeError`:
```
Traceback (most recent call last):
  File "../miniconda3/envs/cmortest4forge/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.5.0', 'console_scripts', 'PrePARE')()
  File "/home/wachsmann/miniconda3/envs/cmortest4forge/lib/python3.6/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 886, in main
    sys.stdout.write(f.read())
  File "/home/wachsmann/miniconda3/envs/cmortest4forge/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 19342: invalid start byte
```
This is where I am lost right now. Can anyone help?

Best regards and thanks,
Fabi

**Comment by mauzey1** [comment]
@wachsylon We are about to release CMOR 3.6.0 today on conda-forge, but we could also make another build for 3.5.0.

**Comment by wachsylon** [comment]
Great, no need then for 3.5.0.

**Comment by mauzey1** [comment]
@wachsylon Did the release of CMOR 3.6.0 solve your issue?

**Comment by wachsylon** [comment]
Yes! Its working again. Thank you very much!
