### ISSUE TITLE
Conflict between ossuuid and libuuid

### ISSUE THREAD

**Issue by xylar** [conda-forge/cmor-feedstock#9]
The same conflicts between ossuuid and libuuid occur here as reported in:
https://github.com/PCMDI/cmor/issues/458
https://github.com/conda-forge/libcf-feedstock/issues/20

**Comment by mauzey1** [comment]
This has been resolved by the release of CMOR 3.5.0
https://github.com/PCMDI/cmor/releases/tag/3.5.0
